spring.application.name=demo

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET:9fK7vQx2LzP8mR4sTnW6yB1aC3dE5FgH7JkL0uV9XoI2pS8qR6tYwZ4A1bC3D5eF7G8HjK9LmN0PqRsTuVwXyZ1234567890!@#$%^&*()-_=+[]{}|;:,.<>?}
server.port=${PORT:8080}

