spring.application.name=demo

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://tramway.proxy.rlwy.net:31359/railway}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:hafizjavadev28}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=${SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET:9fK7vQx2LzP8mR4sTnW6yB1aC3dE5FgH7JkL0uV9XoI2pS8qR6tYwZ4A1bC3D5eF7G8HjK9LmN0PqRsTuVwXyZ1234567890}

server.port=${PORT:8080}

